#!/bin/sh

set -eux

cargo build --release
sudo install -d /usr/local/lib/systemd/user-generators/
sudo install -t /usr/local/lib/systemd/user-generators/ target/release/restic-generator 
systemctl --user daemon-reload
